---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: control-api-apiserver
rules:
- apiGroups:
  - ""
  resourceNames:
  - extension-apiserver-authentication
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - groups
  - serviceaccounts
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appuio.io
  resources:
  - organizationmembers
  verbs:
  - create
  - delete
  - edit
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appuio.io
  resources:
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - billing.appuio.io
  - rbac.appuio.io
  resources:
  - billingentities
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - flowcontrol.apiserver.k8s.io
  resources:
  - flowschemas
  - prioritylevelconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - organization.appuio.io
  resources:
  - organizations
  verbs:
  - create
  - delete
  - edit
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.appuio.io
  resources:
  - invitations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.appuio.io
  resources:
  - invitations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.appuio.io
  resources:
  - organizations
  verbs:
  - create
  - delete
  - edit
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.appuio.io
  - user.appuio.io
  resources:
  - invitations
  verbs:
  - delete
  - edit
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - edit
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - edit
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - user.appuio.io
  resources:
  - invitations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - user.appuio.io
  resources:
  - invitations/status
  verbs:
  - get
  - patch
  - update
