---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-user-appuio-io-v1-invitation
  failurePolicy: Fail
  name: validate-invitations.user.appuio.io
  rules:
  - apiGroups:
    - user.appuio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - invitations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-appuio-io-v1-user
  failurePolicy: Fail
  name: validate-users.appuio.io
  rules:
  - apiGroups:
    - appuio.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
  sideEffects: None
