apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.organization.appuio.io
spec:
  insecureSkipTLSVerify: true
  group: organization.appuio.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: control-api-apiserver
    namespace: control-api
  version: v1

