//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingEntity) DeepCopyInto(out *BillingEntity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingEntity.
func (in *BillingEntity) DeepCopy() *BillingEntity {
	if in == nil {
		return nil
	}
	out := new(BillingEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BillingEntity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingEntityAddress) DeepCopyInto(out *BillingEntityAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingEntityAddress.
func (in *BillingEntityAddress) DeepCopy() *BillingEntityAddress {
	if in == nil {
		return nil
	}
	out := new(BillingEntityAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingEntityContact) DeepCopyInto(out *BillingEntityContact) {
	*out = *in
	if in.Emails != nil {
		in, out := &in.Emails, &out.Emails
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingEntityContact.
func (in *BillingEntityContact) DeepCopy() *BillingEntityContact {
	if in == nil {
		return nil
	}
	out := new(BillingEntityContact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingEntityList) DeepCopyInto(out *BillingEntityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BillingEntity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingEntityList.
func (in *BillingEntityList) DeepCopy() *BillingEntityList {
	if in == nil {
		return nil
	}
	out := new(BillingEntityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BillingEntityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingEntitySpec) DeepCopyInto(out *BillingEntitySpec) {
	*out = *in
	if in.Emails != nil {
		in, out := &in.Emails, &out.Emails
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Address = in.Address
	in.AccountingContact.DeepCopyInto(&out.AccountingContact)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingEntitySpec.
func (in *BillingEntitySpec) DeepCopy() *BillingEntitySpec {
	if in == nil {
		return nil
	}
	out := new(BillingEntitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingEntityStatus) DeepCopyInto(out *BillingEntityStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingEntityStatus.
func (in *BillingEntityStatus) DeepCopy() *BillingEntityStatus {
	if in == nil {
		return nil
	}
	out := new(BillingEntityStatus)
	in.DeepCopyInto(out)
	return out
}
