apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: control-api:basic-user
rules:
# Allow kubectl to validate CRDs
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "watch", "list"]

- apiGroups: ["organization.appuio.io"]
  resources: ["organizations"]
  verbs: ["get", "watch", "list", "patch", "update", "create"]
- apiGroups: ["rbac.appuio.io"]
  resources: ["organizations"]
  verbs: ["watch", "list", "create"]
- apiGroups: ["appuio.io"]
  resources: ["zones"]
  verbs: ["get", "watch", "list"]
# BillingEntity
# `get` permissions are created manually or when creating a new BillingEntity
- apiGroups: ["rbac.appuio.io"]
  resources: ["billingentities"]
  verbs: ["create", "watch", "list"]
- apiGroups: ["billing.appuio.io"]
  resources: ["billingentities"]
  verbs: ["create", "get", "watch", "list"]
# Invitation
# `get` permissions are created when creating a new BillingEntity
- apiGroups: ["rbac.appuio.io"]
  resources: ["invitations"]
  verbs: ["watch", "list"]
- apiGroups: ["user.appuio.io"]
  resources: ["invitations"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["rbac.appuio.io", "user.appuio.io"]
  resources: ["invitations"]
  verbs: ["create"]
# Allow redeeming invitations
- apiGroups: ["user.appuio.io"]
  resources: ["invitationredeemrequests"]
  verbs: ["create"]
