apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: control-api:basic-user
rules:
- apiGroups: ["organization.appuio.io"]
  resources: ["organizations"]
  verbs: ["get", "watch", "list", "patch", "update", "create"]
- apiGroups: ["rbac.appuio.io"]
  resources: ["organizations"]
  verbs: ["watch", "list", "create"]
- apiGroups: ["appuio.io"]
  resources: ["zones"]
  verbs: ["get", "watch", "list"]
# BillingEntity
# `get` permissions are created manually or when creating a new BillingEntity
- apiGroups: ["rbac.appuio.io"]
  resources: ["billingentities"]
  verbs: ["watch", "list"]
- apiGroups: ["billing.appuio.io"]
  resources: ["billingentities"]
  verbs: ["get", "watch", "list"]
# Invitation
# `get` permissions are created when creating a new BillingEntity
- apiGroups: ["rbac.appuio.io"]
  resources: ["invitations"]
  verbs: ["watch", "list", "redeem"]
- apiGroups: ["user.appuio.io"]
  resources: ["invitations"]
  # empty verb to allow upstream server to pass custom verbs to our aggregated API server
  verbs: ["get", "watch", "list", "redeem", ""]
