apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: control-api:organization-admin
rules:
- apiGroups: ["rbac.appuio.io"] 
  resources: ["organizations"]
  verbs: ["get", "watch", "list", "patch", "update", "create"]
- apiGroups: ["appuio.io"] 
  resources: ["organizationmembers"]
  verbs: ["get", "watch", "list", "patch", "update"]
- apiGroups: ["appuio.io"]
  resources: ["teams"]
  verbs: ["get", "watch", "list", "patch", "update", "create", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["get", "watch", "list", "patch", "update", "create"]
