---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: control-api-controller
rules:
- apiGroups:
  - appuio.io
  resources:
  - users
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appuio.io
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
